### ISSUE TITLE
Pre-1.0_03-beta - Translation rework

### ISSUE THREAD

**Issue by tristantheb** [tristantheb/Luna-French#5]
- [x] **Fixe** File corruption #4
- [x] **Fixe** Translation of "fly-out"
- [x] **Fixe** Translation of time format (yyyy-mm-dd to jj-mm-aaaa)
- [x] **Fixe** Translation "fil/fils" is wrong, changed to "sujet/sujets"
- [x] **Fixe** Description of moderate button have a wrong button name

Please, add your feedback of test here

**Comment by Frank201** [comment]
Issue #4 fixed correctly + Fixes of version 1.0_02 is correctly added

**Comment by tristantheb** [comment]
Problems solved
