### ISSUE TITLE
By/Par

### ISSUE THREAD

**Issue by Cotopaxi42** [tristantheb/Luna-French#7]
Salut,

Petit soucis sur la trad, qui revient tout le temps. Quand on voit la liste de posts, il y a une faute au niveau du pseudo de la personne qui a posté.
Au lieu de Par tristantheb (By tristantheb), il est écrit Pas tristantheb. 
Je n'arrive pas à remplacer le s par un r, comment faire ?

Merci !

**Comment by tristantheb** [comment]
Bonjour,

Merci pour le signalement, j'ai trouvé où était la petite faute de frappe, c'est corrigé et uploadé : https://github.com/tristantheb/Luna-French/releases/tag/1.0.1-release
